// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";

/// @notice Proves the Solidity EIP-712 encoding for `WithdrawCommand` and
///         `WithdrawalAuthorization` is byte-identical to viem's (the TS
///         signing path). The expected digests are generated by viem and also
///         asserted in the shared package's TS test, so both languages agree.
contract EIP712ParityTest is Test {
    // Fixed domain/inputs shared with the TS parity test.
    bytes32 constant DOMAIN_TYPEHASH =
        keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)");
    address constant VERIFYING_CONTRACT = 0x00000000000000000000000000000000000000AA;
    uint256 constant CHAIN_ID = 8453;

    bytes32 constant GAME_ID = bytes32(uint256(0x1111111111111111111111111111111111111111111111111111111111111111));
    bytes32 constant SHADOW = bytes32(uint256(0x2222222222222222222222222222222222222222222222222222222222222222));
    address constant OWNER = 0x00000000000000000000000000000000000000B0;
    address constant RECIPIENT = 0x00000000000000000000000000000000000000d0;
    uint256 constant DEST_CHAIN_ID = 8453;
    address constant DEST_BRIDGE = 0x00000000000000000000000000000000000000D1;
    bytes32 constant USER_CMD_HASH =
        bytes32(uint256(0x3333333333333333333333333333333333333333333333333333333333333333));
    bytes32 constant SHADOW_BURN_REF =
        bytes32(uint256(0x4444444444444444444444444444444444444444444444444444444444444444));
    uint256 constant AMOUNT = 1_000_000;
    uint256 constant NONCE = 7;
    uint256 constant DEADLINE = 1_893_456_000;
    uint256 constant SHADOW_CHAIN_ID = 1337;

    bytes32 constant EXPECTED_CMD = 0x7f4b8e38242cccc74796f16a0086ef24cec752bd3ae4794839f973a6f6de522e;
    bytes32 constant EXPECTED_AUTH = 0xb64dc6968a21faa236bf3fdb38f6a565b0193823039cd6b3b4b6309af9929520;

    function _domainSeparator() internal pure returns (bytes32) {
        return keccak256(
            abi.encode(
                DOMAIN_TYPEHASH,
                keccak256(bytes("DarkBoxBridge")),
                keccak256(bytes("1")),
                CHAIN_ID,
                VERIFYING_CONTRACT
            )
        );
    }

    function test_WithdrawCommandDigestMatchesViem() public pure {
        bytes32 typeHash = keccak256(
            "WithdrawCommand(bytes32 gameId,address owner,bytes32 shadowAccount,uint256 amount,address recipient,uint256 destinationChainId,address destinationBridge,uint256 nonce,uint256 deadline,uint256 shadowChainId)"
        );
        bytes32 structHash = keccak256(
            abi.encode(
                typeHash,
                GAME_ID,
                OWNER,
                SHADOW,
                AMOUNT,
                RECIPIENT,
                DEST_CHAIN_ID,
                DEST_BRIDGE,
                NONCE,
                DEADLINE,
                SHADOW_CHAIN_ID
            )
        );
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", _domainSeparator(), structHash));
        assertEq(digest, EXPECTED_CMD);
    }

    function test_WithdrawalAuthorizationDigestMatchesViem() public pure {
        bytes32 typeHash = keccak256(
            "WithdrawalAuthorization(bytes32 gameId,address owner,bytes32 shadowAccount,uint256 amount,address recipient,uint256 destinationChainId,address destinationBridge,bytes32 userCommandHash,bytes32 shadowBurnRef,uint256 nonce,uint256 deadline)"
        );
        bytes32 structHash = keccak256(
            abi.encode(
                typeHash,
                GAME_ID,
                OWNER,
                SHADOW,
                AMOUNT,
                RECIPIENT,
                DEST_CHAIN_ID,
                DEST_BRIDGE,
                USER_CMD_HASH,
                SHADOW_BURN_REF,
                NONCE,
                DEADLINE
            )
        );
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", _domainSeparator(), structHash));
        assertEq(digest, EXPECTED_AUTH);
    }
}
