#!/usr/bin/env node
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { arcTestnet, toEnv } from "./index.js";

/**
 * Emit the public Arc-testnet env vars (derived from the canonical in-repo
 * deploy artifact) to `.env.arc-testnet` at the repo root. The file is
 * gitignored — re-run after a redeploy refreshes the artifact, then load it
 * alongside the sealed secrets env.
 */
const env = toEnv(arcTestnet);
const body =
  `# Generated by @darkbox/deployments from packages/contracts/deployments (${arcTestnet.canonicalMarket.question}).\n` +
  "# Do not edit by hand — re-run `pnpm --filter @darkbox/deployments gen-env` after a redeploy.\n" +
  Object.entries(env)
    .map(([key, value]) => `${key}=${value}`)
    .join("\n") +
  "\n";

const outPath = fileURLToPath(new URL("../../../.env.arc-testnet", import.meta.url));
writeFileSync(outPath, body);
console.log(`wrote ${outPath}`);
process.stdout.write(body);
